# syntax=docker/dockerfile:1
#FROM python:3
# This file uses Ubuntu rather than pyhton because this leads to smaller image size.
# Ubuntu does not include all Python versions.
FROM ubuntu:18.04
LABEL maintainer="jussi.niutanen@gmail.com"

COPY . /JiraPython
WORKDIR /JiraPython
#RUN python3 -m pip install --upgrade pip | \
RUN apt-get update \
    && apt-get install -y python3-pip python3 \
    pip3 install -r ./requirements.txt | \
    cp auto_sprint/it_config.yaml /root/it_config.yaml
#RUN cp JiraPython/auto_sprint/it_config.yaml ~/it_config.yaml
#RUN pwd
#CMD ["python3”, "JiraPython/auto_sprint/new_issue.py"]

#WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
#You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
