name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Apikey

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build . --file docker/dockerfile --tag '${{ secrets.DOCKERHUB_USERNAME }}'/jira_python:$(date +%s)
        docker tag jira_python niutanen/jira_python:$(date +%s)
        docker push '${{ secrets.DOCKERHUB_USERNAME }}'/jira_python:$(date +%s)
