name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Apikey

    steps:
    - uses: actions/checkout@v2
    - uses: actions/docker/login@master
      with: # Set the secret as an input
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}    
    - name: Build the Docker image
      run: |
        docker build . --file docker/dockerfile --tag niutanen/jira_python:$(date +%s)
        docker push niutanen/jira_python:$(date +%s)
