name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Apikey

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}    
    - name: Build the Docker image
      run: |
        docker build . --file docker/dockerfile --tag '${{ secrets.DOCKERHUB_USERNAME }}'/jira_python
        docker push '${{ secrets.DOCKERHUB_USERNAME }}'/jira_python
