name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        docker build . --file docker/dockerfile --tag my-image-name:$(date +%s)
        docker push niutanen/jira_python:my-image-name:$(date +%s)
