name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Apikey

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cat ${{ secrets.DOCKERHUB_PASSWORD }} |  docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build . --file docker/dockerfile --tag niutanen/jira_python
        docker push niutanen/jira_python
